### PR TITLE
Fix one important problem and some chores

### PR DESCRIPTION
**Pull request by zinen**
Important:
- Fixed syntax errors (b1e6589)

Chores:
- Typo in module name example (765266c)
- Commit lock file (86f8650)
- Fix and ran lint (8e18c48)
- Only include relevant files in publish (4954c41)
- Optimize images (tests still works) (61e09b8)

### CODE REVIEW

**Comment by dieterwalckiers** [comment]
Much appreciated @zinen 👍

**Comment by zinen** [comment]
Glad you liked it. Mind during a npm publish? I'll like to use your module.

Btw. Love that you based the logic on a papir on the subject. Very scientific 🙂

**Comment by dieterwalckiers** [comment]
Ok, published.
And though I wished, I can't take credit for the logic, I actually copied some of the code from [pixelmatch](github.com/mapbox/pixelmatch).
I credited them in the readme.
This way, this package has 0 dependencies, but if this goes against the standards/morale of open source (I'm relatively new to open source development), we could rewrite so it depends on pixelmatch?

**Comment by zinen** [comment]
I like this repo more as it allows for different sized images to be compared. 

And I would rather depend your repo then on my on own fork as I then get updates if others have some additions to this repo.

**Pull request merged**
